spring.application.name=user-service
server.port=8080

spring.datasource.url=${USER_DATABASE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Enable SQL logging to the console
spring.jpa.show-sql=true
# Correct property to prettify and format the SQL output
spring.jpa.properties.hibernate.format_sql=true
# Optional: Add syntax highlighting (Spring Boot 3+)
spring.jpa.properties.hibernate.highlight_sql=true
# Bind parameter values inside the logging output (instead of '?')
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.flyway.url=${USER_DATABASE_URL}
spring.flyway.user=${POSTGRES_USER}
spring.flyway.password=${POSTGRES_PASSWORD}
spring.flyway.locations=db/migrations/postgres

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# springdoc.swagger-ui.path=/swagger-ui.html