CREATE TABLE ROLES (
    ID   SERIAL      PRIMARY KEY,
    ROLE VARCHAR(50) NOT NULL UNIQUE CHECK (ROLE ~ '\S')
);

CREATE TABLE USERS (
    ID         UUID           PRIMARY KEY,
    EMAIL      VARCHAR(100)   NOT NULL UNIQUE CHECK (EMAIL ~ '\S'),
    NAME       VARCHAR(150)   NOT NULL CHECK (NAME ~ '\S'),
	ROLE_ID    INT            NOT NULL REFERENCES ROLES(ID),
	ACTIVE     BOOLEAN        NOT NULL,
	CREATED_AT TIMESTAMP      NOT NULL
);

INSERT INTO ROLES (ROLE) VALUES ('ADMIN');
INSERT INTO ROLES (ROLE) VALUES ('TECHNICIAN');
INSERT INTO ROLES (ROLE) VALUES ('CLIENT');